# Generated by Django 3.2.6 on 2023-06-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Polish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Polish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Polish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Polish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Polish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Polish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Polish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Polish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Polish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Polish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Polish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Polish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Polish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Polish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Polish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Polish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Polish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id_klienta', models.AutoField(db_column='ID_klienta', primary_key=True, serialize=False)),
                ('imie', models.CharField(db_collation='Polish_CI_AS', db_column='Imie', max_length=40)),
                ('nazwisko', models.CharField(db_collation='Polish_CI_AS', db_column='Nazwisko', max_length=40)),
                ('miasto', models.CharField(db_collation='Polish_CI_AS', db_column='Miasto', max_length=80)),
                ('mail', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Mail', max_length=40, null=True)),
                ('telefon', models.IntegerField(blank=True, db_column='Telefon', null=True, unique=True)),
                ('wzrost', models.IntegerField(blank=True, db_column='Wzrost', null=True)),
                ('waga', models.IntegerField(blank=True, db_column='Waga', null=True)),
            ],
            options={
                'db_table': 'Klient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oplata',
            fields=[
                ('id_oplaty', models.AutoField(db_column='ID_oplaty', primary_key=True, serialize=False)),
                ('kwota', models.IntegerField(db_column='Kwota')),
                ('waluta', models.CharField(db_collation='Polish_CI_AS', db_column='Waluta', max_length=40)),
                ('rodzaj_paragonu', models.CharField(db_collation='Polish_CI_AS', db_column='Rodzaj_paragonu', max_length=40)),
            ],
            options={
                'db_table': 'Oplata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id_pracownika', models.AutoField(db_column='ID_pracownika', primary_key=True, serialize=False)),
                ('imie', models.CharField(db_collation='Polish_CI_AS', db_column='Imie', max_length=40)),
                ('nazwisko', models.CharField(db_collation='Polish_CI_AS', db_column='Nazwisko', max_length=40)),
                ('data_zatrudnienia', models.DateTimeField(db_column='Data_zatrudnienia')),
            ],
            options={
                'db_table': 'Pracownicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id_roweru', models.AutoField(db_column='ID_roweru', primary_key=True, serialize=False)),
                ('marka', models.CharField(db_collation='Polish_CI_AS', db_column='Marka', max_length=40)),
                ('koszt', models.IntegerField(db_column='Koszt')),
                ('wysokosc', models.CharField(db_collation='Polish_CI_AS', db_column='Wysokosc', max_length=40)),
                ('kolor', models.CharField(db_collation='Polish_CI_AS', db_column='Kolor', max_length=40)),
                ('przeznaczenie_plciowe', models.CharField(db_collation='Polish_CI_AS', db_column='Przeznaczenie_plciowe', max_length=6)),
                ('material_ramy', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Material_ramy', max_length=40, null=True)),
                ('rodzaj_roweru', models.CharField(db_collation='Polish_CI_AS', db_column='Rodzaj_roweru', max_length=40)),
            ],
            options={
                'db_table': 'Rower',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id_salonu', models.AutoField(db_column='ID_salonu', primary_key=True, serialize=False)),
                ('miasto', models.CharField(db_collation='Polish_CI_AS', db_column='Miasto', max_length=40)),
                ('ulica', models.CharField(db_collation='Polish_CI_AS', db_column='Ulica', max_length=80)),
            ],
            options={
                'db_table': 'Salon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wypozyczenia',
            fields=[
                ('id_wypozyczenia', models.AutoField(db_column='ID_wypozyczenia', primary_key=True, serialize=False)),
                ('data_wypozyczenia', models.DateTimeField(db_column='Data_wypozyczenia')),
                ('data_zwrotu', models.DateTimeField(db_column='Data_zwrotu')),
            ],
            options={
                'db_table': 'Wypozyczenia',
                'managed': False,
            },
        ),
    ]
